# Generated by Django 2.1.7 on 2019-03-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compete_details',
            fields=[
                ('challenge_name', models.CharField(max_length=50)),
                ('challenge_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('challenge_status', models.CharField(max_length=10)),
                ('start_time', models.DateTimeField(blank=True)),
                ('end_time', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='problem_details',
            fields=[
                ('challenge_code', models.CharField(max_length=10)),
                ('problem_name', models.CharField(max_length=10)),
                ('problem_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('difficulty', models.CharField(max_length=10)),
            ],
        ),
    ]
