# Generated by Django 2.1.7 on 2019-03-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='submissions',
            fields=[
                ('sub_num', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('problem_code', models.CharField(max_length=10)),
                ('challnge_name', models.CharField(max_length=50)),
                ('sub_status', models.BooleanField(default=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
